### ISSUE TITLE
The "RAID1 - Mostly OK - one chance at mounting read-write" issue was fixed in 4.14

### ISSUE THREAD

**Issue by redneb** [mosteo/btrfs-status#1]
> RAID1 │ Mostly OK │ Failure may give you only one chance at mounting read-write for rebuild

I think this was fixed in 4.14. There are two commits that seem to touch the code that caused this: [21634a19](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=21634a19f6467674ef67fba9714c835a1c0a1e67), [4330e183](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4330e183c9537df20952d4a9ee142c536fb8ae54). The [pull request](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=66ba772ee3119849fcdd8ac9766c6c25ede4a982) for 4.14 says:

> degraded read-write mount is allowed if all the raid profile constraints are met, now based on more accurate check

and the [changelog](https://btrfs.wiki.kernel.org/index.php?title=Changelog&oldid=32621#v4.14_.28Nov_2017.29) in the wiki says:

> fine-grained check for degraded mount (verify raid constraints on chunk level, not device level)

Finally, I did my own (rudimentary) experiment where I was able to do a degraded read-write mount of a RAID1 fs where one of the two drives was missing, and I was able to do that multiple times (I made sure to write some data each time).

**Comment by mosteo** [comment]
Thanks for the heads-up, I'll update that.
